name: Deploy to AWS Lambda

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy-golive-discord-message:
    uses: ./.github/workflows/deployLambda.yml@main
    with:
      lambdaName: golive-discord-message
    secrets:
      jsonSecrets: ${{ secrets.LAMBDA_DISCORD_GOLIVE_MESSAGE_JSON }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
